var annotated =
[
    [ "jsonv", null, [
      [ "detail", null, [
        [ "adapter_builder", "classjsonv_1_1detail_1_1adapter__builder.html", "classjsonv_1_1detail_1_1adapter__builder" ],
        [ "adapter_builder_dsl", "classjsonv_1_1detail_1_1adapter__builder__dsl.html", "classjsonv_1_1detail_1_1adapter__builder__dsl" ],
        [ "basic_owner", "classjsonv_1_1detail_1_1basic__owner.html", "classjsonv_1_1detail_1_1basic__owner" ],
        [ "basic_owning_view", "classjsonv_1_1detail_1_1basic__owning__view.html", "classjsonv_1_1detail_1_1basic__owning__view" ],
        [ "basic_view", "classjsonv_1_1detail_1_1basic__view.html", "classjsonv_1_1detail_1_1basic__view" ],
        [ "formats_builder_dsl", "classjsonv_1_1detail_1_1formats__builder__dsl.html", "classjsonv_1_1detail_1_1formats__builder__dsl" ],
        [ "generic_container", "classjsonv_1_1detail_1_1generic__container.html", "classjsonv_1_1detail_1_1generic__container" ],
        [ "member_adapter", "classjsonv_1_1detail_1_1member__adapter.html", "classjsonv_1_1detail_1_1member__adapter" ],
        [ "member_adapter_builder", "classjsonv_1_1detail_1_1member__adapter__builder.html", "classjsonv_1_1detail_1_1member__adapter__builder" ],
        [ "member_adapter_impl", "classjsonv_1_1detail_1_1member__adapter__impl.html", "classjsonv_1_1detail_1_1member__adapter__impl" ],
        [ "scope_exit_invoker", "classjsonv_1_1detail_1_1scope__exit__invoker.html", "classjsonv_1_1detail_1_1scope__exit__invoker" ],
        [ "string_view", "classjsonv_1_1detail_1_1string__view.html", "classjsonv_1_1detail_1_1string__view" ],
        [ "value_storage", "unionjsonv_1_1detail_1_1value__storage.html", "unionjsonv_1_1detail_1_1value__storage" ]
      ] ],
      [ "adapter", "classjsonv_1_1adapter.html", "classjsonv_1_1adapter" ],
      [ "adapter_for", "classjsonv_1_1adapter__for.html", "classjsonv_1_1adapter__for" ],
      [ "container_adapter", "classjsonv_1_1container__adapter.html", "classjsonv_1_1container__adapter" ],
      [ "context_base", "classjsonv_1_1context__base.html", "classjsonv_1_1context__base" ],
      [ "diff_result", "structjsonv_1_1diff__result.html", "structjsonv_1_1diff__result" ],
      [ "dynamic_merge_rules", "classjsonv_1_1dynamic__merge__rules.html", "classjsonv_1_1dynamic__merge__rules" ],
      [ "encoder", "classjsonv_1_1encoder.html", "classjsonv_1_1encoder" ],
      [ "extraction_context", "classjsonv_1_1extraction__context.html", "classjsonv_1_1extraction__context" ],
      [ "extraction_error", "classjsonv_1_1extraction__error.html", "classjsonv_1_1extraction__error" ],
      [ "extractor", "classjsonv_1_1extractor.html", "classjsonv_1_1extractor" ],
      [ "extractor_construction", "classjsonv_1_1extractor__construction.html", "classjsonv_1_1extractor__construction" ],
      [ "extractor_for", "classjsonv_1_1extractor__for.html", "classjsonv_1_1extractor__for" ],
      [ "formats", "classjsonv_1_1formats.html", "classjsonv_1_1formats" ],
      [ "formats_builder", "classjsonv_1_1formats__builder.html", "classjsonv_1_1formats__builder" ],
      [ "function_adapter", "classjsonv_1_1function__adapter.html", "classjsonv_1_1function__adapter" ],
      [ "function_extractor", "classjsonv_1_1function__extractor.html", "classjsonv_1_1function__extractor" ],
      [ "function_serializer", "classjsonv_1_1function__serializer.html", "classjsonv_1_1function__serializer" ],
      [ "kind_error", "classjsonv_1_1kind__error.html", "classjsonv_1_1kind__error" ],
      [ "merge_rules", "classjsonv_1_1merge__rules.html", "classjsonv_1_1merge__rules" ],
      [ "no_extractor", "classjsonv_1_1no__extractor.html", "classjsonv_1_1no__extractor" ],
      [ "no_serializer", "classjsonv_1_1no__serializer.html", "classjsonv_1_1no__serializer" ],
      [ "ostream_encoder", "classjsonv_1_1ostream__encoder.html", "classjsonv_1_1ostream__encoder" ],
      [ "ostream_pretty_encoder", "classjsonv_1_1ostream__pretty__encoder.html", "classjsonv_1_1ostream__pretty__encoder" ],
      [ "parse_error", "classjsonv_1_1parse__error.html", "classjsonv_1_1parse__error" ],
      [ "parse_options", "classjsonv_1_1parse__options.html", "classjsonv_1_1parse__options" ],
      [ "path", "classjsonv_1_1path.html", "classjsonv_1_1path" ],
      [ "path_element", "classjsonv_1_1path__element.html", "classjsonv_1_1path__element" ],
      [ "recursive_merge_rules", "classjsonv_1_1recursive__merge__rules.html", "classjsonv_1_1recursive__merge__rules" ],
      [ "serialization_context", "classjsonv_1_1serialization__context.html", "classjsonv_1_1serialization__context" ],
      [ "serializer", "classjsonv_1_1serializer.html", "classjsonv_1_1serializer" ],
      [ "serializer_for", "classjsonv_1_1serializer__for.html", "classjsonv_1_1serializer__for" ],
      [ "throwing_merge_rules", "classjsonv_1_1throwing__merge__rules.html", "classjsonv_1_1throwing__merge__rules" ],
      [ "tokenizer", "classjsonv_1_1tokenizer.html", "classjsonv_1_1tokenizer" ],
      [ "validation_error", "classjsonv_1_1validation__error.html", "classjsonv_1_1validation__error" ],
      [ "value", "classjsonv_1_1value.html", "classjsonv_1_1value" ],
      [ "version", "structjsonv_1_1version.html", "structjsonv_1_1version" ]
    ] ],
    [ "std", null, [
      [ "hash< jsonv::value >", "structstd_1_1hash_3_01jsonv_1_1value_01_4.html", "structstd_1_1hash_3_01jsonv_1_1value_01_4" ]
    ] ]
];